# Generated by Django 4.1 on 2022-09-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_task_id', models.IntegerField(editable=False)),
                ('task_completed_at', models.DateField(auto_now=True)),
                ('task_status', models.BooleanField(default=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=30, verbose_name='title')),
                ('task_description', models.CharField(max_length=100, verbose_name='description')),
                ('task_date', models.DateTimeField(verbose_name='date')),
                ('task_status', models.BooleanField(default=False, editable=False)),
            ],
        ),
    ]
